FROM node:18-alpine AS builder
LABEL Developers="Robert Pisarek"
RUN apk add --no-cache git
WORKDIR /app
RUN git clone https://github.com/Robertx999/svelte-web-esp32-cam-gallery.git
RUN npm ci
RUN npm run build
RUN rm -rf src/ static/ server/ esp32_firmware/ node_modules

FROM node:18-alpine
COPY --from=builder /app/build .
USER node:node
EXPOSE 3000
CMD ["node","build/"]